# This is a basic workflow to help you get started with Actions

name: Update oisd auto

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */4 * * *"
  push:
    branches:
      - main    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Run oisd update
        run: cd oisd/ && chmod +x update_oisd.sh && bash update_oisd.sh
        
      - uses: stefanzweifel/git-auto-commit-action@v5
