# This is a basic workflow to help you get started with Actions

name: Update data auto

on:
  workflow_dispatch:
  schedule:
    - cron: "30 */4 * * *"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Run data update
        run: |
          mkdir tmp && cd tmp
          wget https://github.com/SagerNet/sing-box/releases/download/v1.8.10/sing-box-1.8.10-linux-amd64.tar.gz
          tar xf *.tar.gz && mv sing-box-1.8.10-linux-amd64/sing-box /usr/local/bin/ && cd .. && rm tmp -r
          cd cdn/ && chmod +x update.sh && bash update.sh && cd ..
          cd oisd/ && chmod +x update.sh && bash update.sh

      - uses: stefanzweifel/git-auto-commit-action@v5
